### PR TITLE
Footer enhance

### LINKED ISSUE #44: Enhancemnet of footer
Footer is looking very simple. i want to make some changes in it like logo and some info of class deck and class deck social media handlers etc.

### PR DESCRIPTION
**Pull request by Abhishek2408**
## Related Issue or bug
  - Footer of the site looks very simple

Fixes: #44 

#### Describe the changes you've made
I have added logo of site along with its description and also added social icon using that user can diverted to class Deck social media make make enhancement in footer and it is responsive too

## Type of change

- [x] Code style update (formatting, local variables)

## How Has This Been Tested?

I have tested it on my local machine on various screen sizes of desktop as well as mobile..

## Checklist:

- [x] Have you checked there aren't other open Pull Requests for the same update/change?
- [x] My submission doesn't break any existing feature.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x]Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 
image
  | 
image
 |

### CODE REVIEW

**Comment by coding-geek21** [comment]
can you place this text  " _ClassDeck aims to provide a virtual classroom that breaks the synchronous hurdles of location, place, student limits and cater the knowledge to the learning crowd anytime and anywhere_" instead of lorem ipsum

**Comment by Abhishek2408** [comment]
@coding-geek21 ya sure

**Comment by coding-geek21** [comment]
> @coding-geek21 ya sure

Also do `git pull` so that your branch is updated

**Review by coding-geek21 — CHANGES_REQUESTED** [review]
Please don't delete `.env_template` file you have deleted it. so add that file again

**Comment by Abhishek2408** [comment]
@coding-geek21 can u tell me how to create that .env file?

**Comment by Abhishek2408** [comment]
@coding-geek21

**Pull request merged**
