### PR TITLE
First

### PR DESCRIPTION
**Pull request by Kritinp**
## Related Issue or bug
  - Info about Issue or bug

Fixes: 
#[11]
#[31]

#### Describe the changes you've made
UI of the webpage where quizes are viewed have been changed to make it look cleaner. Image on the left side disappears on mobile devices and table has been made responsive.
UI of create quiz has been enhanced similarly.
HomePage has been changed slightly to enable smooth scrolling on clicking on "read more"
Screenshot from 2022-03-05 10-02-40
Screenshot from 2022-03-05 10-03-02

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [ ] Have you checked there aren't other open Pull Requests for the same update/change?
- [ ] My submission doesn't break any existing feature.
- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by coding-geek21** [comment]
@Kritinp Good work! UI looks great can you make it responsive too

image

**Comment by Kritinp** [comment]
> @Kritinp Good work! UI looks great can you make it responsive too
> 
> image

Thanks!
Do you mean responsive with respect to the size of the window or something else?

**Comment by coding-geek21** [comment]
> > @Kritinp Good work! UI looks great can you make it responsive too
> > image
> 
> Thanks! Do you mean responsive with respect to the size of the window or something else?

You can see that main content is overlapping with navbar right.. that one

**Comment by coding-geek21** [comment]
@Kritinp any updates??

**Comment by coding-geek21** [comment]
@Kritinp When will you complete this? it's more than 5 days

**Comment by Kritinp** [comment]
> @Kritinp When will you complete this? it's more than 5 days

Will finish it tonight

**Comment by Kritinp** [comment]
> @Kritinp When will you complete this? it's more than 5 days

I have updated the pull request. Please let me know if any changes are to be made.

**Review by coding-geek21 — APPROVED** [review]
Looks Good!
Would you like to make all these pages mobile responsive in a new isse? 

image

**Pull request merged**
