### PR TITLE
Issue #46 Forgot password feature

### LINKED ISSUE #46: Add forgot password feature
## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

## Define You

- [ ] GSSoC22 Participant
- [ ] Contributor

## Is your feature request related to a problem? Please describe.

Create forgot password feature

## Approach to be followed (optional):

- add forgot password link in login page
- on clicking the link it should ask the email of the user
- check if the user is available in users list (backend)
- if found send the link for password reset through mail and display message "Password reset link sent to your mail"
- on clicking the link in mail user should get redirected to form asking new password and confirm password
-  Display message "Successfully updated password"

## Screenshots Or Video

Attach screenshots or video if applicable

### PR DESCRIPTION
**Pull request by m-a-rahul**
Fixes: #46

## Description
Built custom templates with UI features relating to the ClassDeck's classic structure, on **top of django.contrib.auth.views** which offers default authentication feature by also handling form errors.

### Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

The feature has been tested across multiple times and is completely error free as we have just customised the default django package.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)

- There is a specific place where Django captures the protocol and domain by default in **password_reset_email.html**
- In the development environment, while running on **localhost** Django identifies the domain as **example.com**. 
- So I had to make it statically as **localhost:8000**. I have also attached the code for the production environment in commented format.

#### password_reset_email.html
`line no 5: {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}`  <- Production _(commented)_        
`line no 6: http://localhost:8000{% url 'password_reset_confirm' uidb64=uid token=token %}` <- Development _(active)_

## Checklist:

- [x] Have you checked there aren't other open Pull Requests for the same update/change?
- [x] My submission doesn't break any existing feature.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.

## Successfull Testcase
image
image
image
image
image

## Invalid token
_(If an attacker tries with another token and access the URL or if the same token is used twice)_
 
image

### CODE REVIEW

**Comment by coding-geek21** [comment]
There is one bug @m-a-rahul 

- When I click on login here and try submitting my credentials it shows invalid credentials, and when I enter my old password I'm able to login.. So it means the new password is not updated in backend yet.. Please check this bug and resolve it

- Also when submitting the mail in form for sending password reset link, it should check whether the mail id is present in the database... if its not present display the message like user with this mail id doesn't exit. If the mail id exist then only you should display the message like mail sent and send the email with that link

**Review by coding-geek21 — CHANGES_REQUESTED** [review]
There is one bug @m-a-rahul
 
 * When I click on login here and try submitting my credentials it shows invalid credentials, and when I enter my old password I'm able to login.. So it means the new password is not updated in backend yet.. Please check this bug and resolve it
 * Also when submitting the mail in form for sending password reset link, it should check whether the mail id is present in the database... if its not present display the message like user with this mail id doesn't exit. If the mail id exist then only you should display the message like mail sent and send the email with that link

**Comment by yaswanthsaivendra** [comment]
@m-a-rahul  Usually when we have differentiating stuff b/w development & prod code, its better make use of a simple if-else rather than commenting stuff. What we can do is just make use of `DEBUG` constant with `if statement` and check whether if its set to true then implement the dev. code  else prod. code.

**Comment by m-a-rahul** [comment]
Ok cool, got your suggestions. Will write back asap on completion of the changes requested.

**Comment by m-a-rahul** [comment]
## Fixes after the previous set of suggestions

### Fix 1 
**Corresponding bug:** Password Update Failure
**Description:** 
_Cause_ -> Since an AbstractUser model is configured on top of the default Users model the password update didn't work.
_Fix_ -> Built a custom form on top `SetPasswordForm`, which handles this functionality in the Django package

### Fix 2 
**Corresponding bug:** Email Check
**Description:** 
_Cause_ -> Django's default form doesn't inherit the functionality.
_Fix_ -> Built a custom form on top `PasswordResetForm`, which handles this functionality in the Django package

**Screenshot:** 
image

### Fix 3
**Corresponding bug:** Domain name in dev and prod env
**Description:** 
_Cause_ -> Django uses the sites framework to capture the domain 
_Fix_ -> Wrote a condition to change the domain key value to, 

- `localhost:800` when `DEBUG=True` and 
- `classdeck.herokuapp.com` when `DEBUG=False`

**Screenshot:** 
sketchpad pro_F4E6D533E0B94758D48

**Review by coding-geek21 — APPROVED** [review]
Great work! merging it

**Pull request merged**
