### PR TITLE
Final issue#25

### LINKED ISSUE #25: Enhancement of Navbar
The navbar can be improved, it look odd here.I can improve the UI of that, please assign this issue under gssoc'22 and I would like to work on it

### PR DESCRIPTION
**Pull request by HarshKumarChoudary**
# Fixed navbar enhancement issue.

# Fixes: #25

Here I changed the navbar background to a transparent effect along with change in color upon scroll and also changed the login and signup buttons designs. Also made navbar sticky.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)

## How Has This Been Tested?

used local Django server to test the design.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:

- [x] Have you checked there aren't other open Pull Requests for the same update/change?
- [x] My submission doesn't break any existing feature.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **image**  | <b>
image
</b> |

### CODE REVIEW

**Comment by HarshKumarChoudary** [comment]
This is the enhancement of navbar made. No conflicts and also added space below navbar. Previously suggested implementation is also there. Thanks.

**Comment by coding-geek21** [comment]
@HarshKumarChoudary The navbar doesn't suit the website.. so please remove the changes you did in  background let it be the same like how it was before. 

You just make that message visible below the navbar and not on the navbar..  That's enough

**Review by coding-geek21 — CHANGES_REQUESTED** [review]
See the message is displaying below the form.. It's not in the proper position.. 
It should be above the form ( below navbar )

image

**Comment by HarshKumarChoudary** [comment]
ok I will finish it by tomorrow, since my exams are going on.

**Comment by HarshKumarChoudary** [comment]
I added the changes as suggested, by moving the messages tab below to navbar and above the content. Please review it. Thanks.

**Review by coding-geek21 — APPROVED** [review]

**Pull request merged**
