### PR TITLE
Feature for creating / managing assignments 

### LINKED ISSUE #68: Page for creating and managing assignments
## Define You

- [x] GSSoC22 Participant
- [ ] Contributor

## Is your feature request related to a problem? Please describe.

No page for creating , posting and managing  assignments .

## Describe the solution you'd like...

I will create a page where teachers will create assignments , upload documents and a email notification system for students about the assignments. Teachers will be able to upload assignments , give description and review the submissions , and score them on the basis of their response .

### PR DESCRIPTION
**Pull request by Ashsenior**
## Related Issue or bug
  - Info about Issue or bug

Fixes: #68 

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [x] Have you checked there aren't other open Pull Requests for the same update/change?
- [x] My submission doesn't break any existing feature.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |
Screenshot (73)
Screenshot (76)
Screenshot (77)](https://user-images.githubusercontent.com/49332381/160377498-979e2346-4d73-4799-bc1f-cd443864c275.png)
m/49332381/160377457-ed490901-f209-4750-ad98-5bf533cda0
Screenshot (80)
Screenshot (81)

c3.png)
Screenshot (78)

Screenshot (75)

### CODE REVIEW

**Comment by Ashsenior** [comment]
I have created , 

**FOR TEACHERS**

Page for viewing all our assignments
Page for creating / updating assignment
Email notification system for students to get notification about newly added assignments
Page to check all responses of students  for each assignment
Page to score the student and give remarks for the response

**FOR STUDENTS**

Page to see all assignments according to the interest of the student
Page to submit a response for any assignment
Page to view the result of his/her assignment .

**Comment by coding-geek21** [comment]
Sorry for viewing the PR after a long time. I was super busy with some works. 

Awesome work actually!  Everything was really perfect

Just one thing i want to ask 

image

I'm not able to update the score and remarks (form is not visible)
and here it shows like checked right but in student's view it showing like unchecked can you clarify this @Ashsenior

**Comment by coding-geek21** [comment]
image
this form is not showing 

image
This checked status is not showing 

Only these two bugs apart from these everything works fine... Can you do these in another issue if you wish? So that i could give level 3 for that new issue.. what's your opinion ?

**Comment by Ashsenior** [comment]
Yeah I can do that 👍

**Comment by coding-geek21** [comment]
> Yeah I can do that 👍

Okay you create that new issue (assignment status check) and i will assign you and then merge this issue

**Comment by Ashsenior** [comment]
> > Yeah I can do that 👍
> 
> Okay you create that new issue (assignment status check) and i will assign you and then merge this issue

i have created this issue and have been assigned . You can merge now if u want . thnx

**Pull request merged**
