### PR TITLE
Channels addition complete configurations

### LINKED ISSUE #30: No option to add a subject(channels feature)
Teacher does not have an option to add a subject. As soon as teacher logs in, he/she should see the 4th option of adding a subject too.
Please assign this issue to me. I like to work on this.

### PR DESCRIPTION
**Pull request by m-a-rahul**
Fixes: #30 

#### Describe the changes you've made
Configured the backend to accept all the functionalities related to channels. 

- Teachers can create new channels.
- Share the link associated with the channel for students to join.
- Students and Teachers can view their channels under `My Channels`
- Students can both `Join` and `Leave` a particular channel.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

#### Describe if there is any unusual behaviour of your code
Kindly look into the front end and clarify if there is any more changes required in the frontend

## Checklist:

- [x] Have you checked there aren't other open Pull Requests for the same update/change?
- [x] My submission doesn't break any existing feature.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.

## Teachers
image
image
image
image

## Students
image
image
image

### CODE REVIEW

**Comment by coding-geek21** [comment]
Looks Good!  @m-a-rahul  Can you take this to the next step like
- Here you have created the channel without linking the subject right so now the teacher should select the subject and then create the channel for that subject
- Students & teacher should be able to chat on those channels
- Channels should show assignments as one tab (It must show all the assignments for that particular subject assigned by that teacher)
- Channels should have exams as one tab (shows exams posted for that subject by that teacher ) 
- Channels should have members as one tab ( list of students and teachers name must be visible)

You can implement all these each as separate level 3 issue

**Review by coding-geek21 — APPROVED** [review]

**Comment by m-a-rahul** [comment]
Yea sure. Happy to help!

But before I start I have a few queries. If we directly relate the assignments and quizzes based on the subject it might lead to confusion according to my view.

Let's say I am a teacher and I have two channels for the subject English but the two channels are for two different grades. So according to our current idealogy, if I create an assignment for English both the grades will be prompted for the submission. Rather directly associating assignments and quizzes with channels will allow the teacher to assign individual tasks to each channel.

Kindly write back at your convenience!

**Comment by coding-geek21** [comment]
> Yea sure. Happy to help!
> 
> But before I start I have a few queries. If we directly relate the assignments and quizzes based on the subject it might lead to confusion according to my view.
> 
> Let's say I am a teacher and I have two channels for the subject English but the two channels are for two different grades. So according to our current idealogy, if I create an assignment for English both the grades will be prompted for the submission. Rather directly associating assignments and quizzes with channels will allow the teacher to assign individual tasks to each channel.
> 
> Kindly write back at your convenience!

Yeah, the assumption is correct. It  might create confusion when we relate subject with channels. Can we relate assignment and 
 quiz with channels? Like adding an other option to select the channel. It is possible right?

**Comment by m-a-rahul** [comment]
In that case, we're revamping the core flow of the project. In a way, we are replacing the subject with the channel and adding it as a byproduct of the same.

So the new flow will be a teacher signs up and creates a channel and add members to the channel via links. Then he/she can create quizzes and assignments for the specific channels and grade them accordingly. The channels will act as a virtual classroom.

**Comment by coding-geek21** [comment]
> In that case, we're revamping the core flow of the project. In a way, we are replacing the subject with the channel and adding it as a byproduct of the same.
> 
> So the new flow will be a teacher signs up and creates a channel and add members to the channel via links. Then he/she can create quizzes and assignments for the specific channels and grade them accordingly. The channels will act as a virtual classroom.

okay so what would be your suggestion?

**Comment by m-a-rahul** [comment]
I am about to give my semester exams for the next two weeks can I have a timesheet after that? I am genuinely interested in your project and feel I can produce some quality deliverables.

**Comment by coding-geek21** [comment]
> I am about to give my semester exams for the next two weeks can I have a timesheet after that? I am genuinely interested in your project and feel I can produce some quality deliverables.

Yeah take your time

**Pull request merged**
