### PR TITLE
Issue#25 Fixing

### LINKED ISSUE #25: Enhancement of Navbar
The navbar can be improved, it look odd here.I can improve the UI of that, please assign this issue under gssoc'22 and I would like to work on it

### PR DESCRIPTION
**Pull request by HarshKumarChoudary**
# Fixed navbar enhancement issue.

# Fixes: #25

Here I changed the navbar background to a gradient effect and also changed the login and signup buttons designs. Also made navbar sticky.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)

## How Has This Been Tested?

used local Django server to test the design.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:

- [x] Have you checked there aren't other open Pull Requests for the same update/change?
- [x] My submission doesn't break any existing feature.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **image**  | <b>
image
</b> |

### CODE REVIEW

**Comment by coding-geek21** [comment]
Button looks odd and background color doesn't suit.. please change it @HarshKumarChoudary

**Comment by HarshKumarChoudary** [comment]
Could you please give me some details about what designs of navbar you would like:
For example.
1) Transparent Navbars.
2) Left Side vertical Navbar.
or what combinations of color will look best for this.

**Comment by coding-geek21** [comment]
> Could you please give me some details about what designs of navbar you would like: For example.
> 
> 1. Transparent Navbars.
> 2. Left Side vertical Navbar.
>    or what combinations of color will look best for this.

- Make a transparent navbar which on scroll down will change back to whatever color is now
refer this : https://codeconvey.com/Tutorials/navbar-transparent-to-solid-on-scroll/

- Also make the notification messages which is displaying on the navbar to down the navbar

**Comment by HarshKumarChoudary** [comment]
I made the new Navbar which shows scrolling effect and changes the color from transparent to present one.
Also I updated the position of messages to be displayed appear down to it.
Please note : In above image Login button appears colorful (red). This happens when mouse is hovering over it. In image I hovered the mouse over it.

**Comment by coding-geek21** [comment]
- Resolve conflicts 
- Add some space below navbar

**Comment by HarshKumarChoudary** [comment]
I guess when I added those files, no conflicts was there. I guess due to another PR merging done few minutes ago, this branch shows conflicting effect. 
I will update the code and add space below navbar and again create a PR by tomorrow morning.

**Comment by HarshKumarChoudary** [comment]
I remade the PR for issue #25  in PR #57 . So I'm closing this PR, as it was having some conflicts. Thanks.

**Pull request closed without merging**
