### PR TITLE
Changing the form shape and managing the alerts messages

### PR DESCRIPTION
**Pull request by muhammadgalhoum**
## Related Issue or bug
  - Info about Issue or bug

Fixes: #[issue number that will be closed through this PR] #47 and #56

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [x] Have you checked there aren't other open Pull Requests for the same update/change?
- [x] My submission doesn't break any existing feature.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by muhammadgalhoum** [comment]
Please review my PR @coding-geek21 
Please add a level 3 to this PR, as I have changed the shape of the form and shown the form problems in the form of alerts and also updated the requirements.txt file and created two pages inside the code, which is considered that I have solved two problems together, so please give me a level 3 for this work

https://user-images.githubusercontent.com/56798376/171067554-f1973e63-73b7-4b6c-86c6-b00ceed75f2f.mp4

**Comment by muhammadgalhoum** [comment]
Please can u help me @Suvraneel @praveenscience
GSSoC is about to finish and so far my PR has not been reviewed, as I wrote many messages on the group for this project and also sent a message to the project admin and there is no response
What should I do?

**Review by coding-geek21 — CHANGES_REQUESTED** [review]
Why did you delete .env_template file ? 
first add that then i will review your PR

**Comment by muhammadgalhoum** [comment]
> Why did you delete .env_template file ? first add that then i will review your PR

Now, You can review again @coding-geek21

**Comment by muhammadgalhoum** [comment]
Can u review it again pls @coding-geek21

**Pull request merged**
