### PR TITLE
Calendar feature added

### LINKED ISSUE #94: Calendar Feature for teachers
## Define You

- [x] GSSoC22 Participant
- [x] Contributor

This feature will keep the records of upcoming events or past events for a teacher like : meetings , GD's, Classes , Quizes, and Assignment deadlines . You can add or remove events from each dates .

@coding-geek21 Please assign this to me and review my previous PR.

### PR DESCRIPTION
**Pull request by Ashsenior**
Fixes: #94 

#### Describe the changes you've made
I have made the feature to initialize a calendar for 12 months with a click and then you can view all the dates , days , current date and no. of events in that day .
I'll be making the events feature inside the calendar in the next issue .
Thank you

- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)

## Checklist:

- [x] Have you checked there aren't other open Pull Requests for the same update/change?
- [x] My submission doesn't break any existing feature.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original         

Screenshot (93)
Screenshot (94)

### CODE REVIEW

**Comment by Ashsenior** [comment]
@coding-geek21 please add the level3 and gssoc22 tag before merging and i'll be creating the next issue today .
thnx

**Comment by coding-geek21** [comment]
> Fixes: #94
> 
> #### Describe the changes you've made
> I have made the feature to initialize a calendar for 12 months with a click and then you can view all the dates , days , current date and no. of events in that day . I'll be making the events feature inside the calendar in the next issue . Thank you
> 
> * [x]  New feature (non-breaking change which adds functionality)
> * [x]  Code style update (formatting, local variables)
> 
> ## Checklist:
> * [x]  Have you checked there aren't other open Pull Requests for the same update/change?
> * [x]  My submission doesn't break any existing feature.
> * [x]  My code follows the style guidelines of this project.
> * [x]  I have performed a self-review of my own code.
> * [x]  I have commented my code, particularly in hard-to-understand areas.
> * [x]  I have made corresponding changes to the documentation.
> * [x]  I have added tests that prove my fix is effective or that my feature works.
> * [x]  New and existing unit tests pass locally with my changes.
> * [x]  Any dependent changes have been merged and published in downstream modules.
> 
> ## Screenshots
> Original
> 
> Screenshot (93) Screenshot (94)

How am I supposed to add events? @Ashsenior

**Comment by coding-geek21** [comment]
@Ashsenior Also I want you to check this..
If I create two quizzes one quiz is working fine, the second one shows like this when I try to save the answer 
It shows that all the questions are already answered... I want you to check this 

image

image

**Comment by Ashsenior** [comment]
@coding-geek21 i have now fixed the quiz error and i have created a new issue to add the events add and manage feature in calendar . Please refer to that.

**Comment by coding-geek21** [comment]
@Ashsenior Sorry I was held up with exams so couldn't check your PR.

**Comment by coding-geek21** [comment]
Resolve these conflict after that I will merge this. Also remove the changes that you have done to quiz because I reverted that PR

**Comment by coding-geek21** [comment]
@Ashsenior Merged your PR... You can proceed with new issue to add the events and manage features in calendar.

Also there is one small bug in quiz page

image

Here the question number should be 1 right it shows 4 and the status in the left pane after saving the answer for that question that particular question should be marked in green (but it still shows like not answered) I want you to fix this issue [These were the previous features that got collapsed after adding new features timer)

**Pull request merged**
