### PR TITLE
Prateek

### PR DESCRIPTION
**Pull request by prateekmohanty63**
Added Email verification after registration.
Once user clicks on link the user account gets activated

### CODE REVIEW

**Review by coding-geek21 — CHANGES_REQUESTED** [review]
image

- getting this error while creating a teacher account 

And i need some changes

-  Once the user clicks on signup button it should show the message like "Check your mail to activate your account" (after sending the mail in the backend)
-  Once the user clicks on the link they received it shouldn't go back to login page, Instead, automatically sign in the user and go to dashboard

**Comment by prateekmohanty63** [comment]
@coding-geek21  I resolved the teacher account problem.

But when the user clicks in login , where should I display the message check your mail to activate your account

According to me it will be better if I redirect the user to the login page and show the message there, Then once the user clicks on mail activtaion link I will forward user to dashboard

**Comment by coding-geek21** [comment]
> 

Yeah you can display the message in login page itself

**Comment by prateekmohanty63** [comment]
@coding-geek21  check now , I have resolved all the issues.
And also applied the changes you asked for.

**Comment by yaswanthsaivendra** [comment]
Currently I can't test how the code is working!!. But the usual procedure should be 
Whenever a new user signup , a flash shows up at the top of the same page stating that the user has `check email to verify account`
Whenever the user clicks on the link , it has to redirected to login page and display a flash message stating that the user `account is verified` and `kindly login`
Directly logging the user after verification could be a possible scenario too but it couldn't be considered as a security best practice coz any person only having credentials is only considered authorized to access the account and any other person with access to user mail should not be able to login to this account.

**Comment by yaswanthsaivendra** [comment]
@prateekmohanty63 , as u mentioned in the issue , the smtp creds (and other API secrets) have to be moved to env variables . I would create an issue for it once this was merged!!
@coding-geek21 , review this pr further!!

**Comment by prateekmohanty63** [comment]
> @prateekmohanty63 , as u mentioned in the issue , the smtp creds (and other API secrets) have to be moved to env variables . I would create an issue for it once this was merged!! @coding-geek21 , review this pr further!!

@yaswanthsaivendra  so should i move them to env variables?

**Comment by yaswanthsaivendra** [comment]
> > @prateekmohanty63 , as u mentioned in the issue , the smtp creds (and other API secrets) have to be moved to env variables . I would create an issue for it once this was merged!! @coding-geek21 , review this pr further!!
> 
> @yaswanthsaivendra so should i move them to env variables?

Yaa, I m thinking of an optimized soln , coz We couldn't instruct everyone to create a new smtp account for local setup.
What we could do is to provide demo creds for them while local setup. This we have to do :
- make use of `django-environ`
- place the demo creds in a file named .env_template ( as placing .env file in VCS is not a gud idea)
- Later we can instruct them to do a copy of this .env_template file to a file named .env while local setup
  - something like `cp .env_template .env` in any bash like shell or manual copying.
@prateekmohanty63 , If u think of any better solution lemme know.

**Review by coding-geek21 — CHANGES_REQUESTED** [review]
I checked the working of the code..  When i sign up as a student it gives me link like this 

image
 
I think it's the link for teachers verification and when I clicked on this link it's showing the teachers dashboard Instead of showing students dashboard 

image

**Comment by prateekmohanty63** [comment]
@coding-geek21 @yaswanthsaivendra  I have also added the env files and now the credentials are not visible
And all the requirements are also implemented and working
Can you now please merge the pr

**Comment by coding-geek21** [comment]
> I checked the working of the code.. When i sign up as a student it gives me link like this
> 
> image
> 
> I think it's the link for teachers verification and when I clicked on this link it's showing the teachers dashboard Instead of showing students dashboard
> 
> image

@prateekmohanty63  Did you check this?

**Comment by prateekmohanty63** [comment]
image
@coding-geek21  when I am putting the urls here it is working

**Comment by prateekmohanty63** [comment]
image
but when i put here , its not working . Can you tell me why is that?

**Comment by prateekmohanty63** [comment]
@coding-geek21 check now I have fixed it

**Comment by prateekmohanty63** [comment]
@coding-geek21 did you check it out?
For students it forwarding to student dashboard  and for teachers to teacher dashboard

**Comment by coding-geek21** [comment]
> Added Email verification after registration. Once user clicks on link the user account gets activated

@yaswanthsaivendra Can you check that env part?

**Comment by prateekmohanty63** [comment]
image
These are the env variables

**Comment by prateekmohanty63** [comment]
image
I have also made a env.example file , so if anyone uses the code they can define the variables easily

**Comment by coding-geek21** [comment]
ok fine.. one change make email field as unique

**Comment by prateekmohanty63** [comment]
:) okay

**Comment by prateekmohanty63** [comment]
image
@coding-geek21 done

**Comment by yaswanthsaivendra** [comment]
> image I have also made a env.example file , so if anyone uses the code they can define the variables easily

- Move the `EMAIL_HOST` to env variable.
- Rename the file `.env.example` to `.env_tempalte`(as the name suggests its a tempalte for creating .env file)
- Add an instruction to readme (local setup) to create a `.env` file and copy the stuff of `.env_template` manually or by using command.
- Place the values for env variables in .env_template(other than ones which are related to email)
@coding-geek21 , If possible register for any smtp mail service like mailgun, mailjet or sendinblue and place those creds in `.env_template` file

**Comment by prateekmohanty63** [comment]
@yaswanthsaivendra  any more changes you want , apart from this?

**Comment by prateekmohanty63** [comment]
@yaswanthsaivendra  How can I place the value of env variables into env_template , then what is the point of making an env,
and git ignoring it?

**Comment by yaswanthsaivendra** [comment]
> @yaswanthsaivendra any more changes you want , apart from this?
That's all
update the requirements file , if neccessary

**Comment by prateekmohanty63** [comment]
> @yaswanthsaivendra How can I place the value of env variables into env_template , then what is the point of making an env, and git ignoring it?

@yaswanthsaivendra  can you please explain this?

**Comment by yaswanthsaivendra** [comment]
> @yaswanthsaivendra How can I place the value of env variables into env_template , then what is the point of making an env, and git ignoring it?

The creds we are placing in .env_template file are like creds of demo services we are providing for development. we won't be using the same ones for production. If we keep them directly in .env file, when we push the code to any deployment service then they will be added as values for the env variables in our code automatically due to name conventions. To avoid using api keys and secret keys of development in production by mistakenly , we do this!!

**Comment by prateekmohanty63** [comment]
@yaswanthsaivendra  so like what value should I assign here, can you please tell me
image

**Comment by yaswanthsaivendra** [comment]
> @yaswanthsaivendra so like what value should I assign here, can you please tell me image

For now, place the same values, we were using earlier . We will update them , When it comes to prod.

**Comment by prateekmohanty63** [comment]
but what about email name and password , those are my personal credentials
can you give me your organiztion credentials?

**Comment by yaswanthsaivendra** [comment]
Yaa that's way I mentioned @coding-geek21 , for doing this. She will be adding those values before merging your pr. You just keep them empty.

**Comment by prateekmohanty63** [comment]
oh ok sure thanks @yaswanthsaivendra I will do it

**Comment by prateekmohanty63** [comment]
@yaswanthsaivendra  check now , I have made the suggested changes

**Comment by yaswanthsaivendra** [comment]
looks great!! please be patient , ur pr will be merged soon!!

**Comment by prateekmohanty63** [comment]
sure @yaswanthsaivendra  , take your time 
And one more request @yaswanthsaivendra  @coding-geek21  , Like if you guys do any project based on django .
Do let me know if I can join you guys ever in the future.
And do ping me if I can help solving any more issues

**Comment by coding-geek21** [comment]
Looks Perfect merging it!

**Comment by coding-geek21** [comment]
> sure @yaswanthsaivendra , take your time And one more request @yaswanthsaivendra @coding-geek21 , Like if you guys do any project based on django . Do let me know if I can join you guys ever in the future. And do ping me if I can help solving any more issues

sure :)

**Comment by coding-geek21** [comment]
> Yaa that's way I mentioned @coding-geek21 , for doing this. She will be adding those values before merging your pr. You just keep them empty.

**Pull request merged**
