### PR TITLE
Added Timer in the Quiz 

### LINKED ISSUE #49: Create timer for quiz
## Is your feature request related to a problem? Please describe.

Create timer feature for quiz 

## Approach to be followed (optional):

-  The quiz page should automatically exit if the time exceeds
-  Time left should be displayed and should be dynamically updating so that user can see it 

## Screenshots Or Video

Attach screenshots or video if applicable

### PR DESCRIPTION
**Pull request by Ashsenior**
## Related Issue or bug
  - Info about Issue or bug

Fixes: #49 

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Screenshots

Screenshot (90)
Screenshot (91)

### CODE REVIEW

**Comment by coding-geek21** [comment]
there is a small bug when we create multiple tests the duration remains the same as the previous one. There should be a separate Duration for each quiz right.. Here the same duration is visible for every quiz that we create..

Please check this..

image
image

**Comment by Ashsenior** [comment]
No problem I'll fix that

**Comment by coding-geek21** [comment]
@Ashsenior 
Also, can you check this 
I'm getting like this when clicking on update/Responses/Delete in teachers assignment section
image

**Comment by Ashsenior** [comment]
> @Ashsenior Also, can you check this I'm getting like this when clicking on update/Responses/Delete in teachers assignment section image

I was having the same problem but i had fixed it and it is currently working fine in my desktop.

**Comment by Ashsenior** [comment]
I was having the same problem but i had fixed it in those previous commits and it is currently working fine in my desktop.

**Comment by coding-geek21** [comment]
Looks good now..  I'm merging this issue now do the rest in the next issue @Ashsenior 
Can you take this to next level? 
For now, the counter is starting from the first when we leave the quiz and start again.. 
We must change that to it must start from where it left.
And then when we keep some questions without selecting the answer.. user won't be able to submit the quiz ( so make the  answer fields as not required )

**Review by coding-geek21 — APPROVED** [review]

**Comment by coding-geek21** [comment]
Also when i update this branch in my local pc 
image
it shows like this when trying to save the answer for one question

C:\Users\dell\Downloads\My projects\flipr\classDeck-develop\classDeck\classDeck\classroom\views\students.py, line 197, in take_quiz
    question = quiz_questions[qno - 1] 

image
also every question is already marked as green 
I want you to fiz this @Ashsenior fix these bug in another issue

**Comment by coding-geek21** [comment]
I'm Reverting this PR since it's not working well better do this after completing that calendar thing

**Pull request merged**
